replicaCount: 1

image:
  repository: eclipse-dataspace/edc
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

env:
  # Nota: queste sono variabili 'dummy' per far partire il container.
  # L’integrazione reale EDC necessita configurazioni aggiuntive (control/data plane, API keys, catalogo, ecc.)
  EDC_API_PORT: "8080"
  EDC_LOG_LEVEL: "INFO"

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

