# Default values for the Eclipse Dataspace Connector chart.
# Override these values per environment as needed.

## Your wildcard domain for ingress.  Replace starktechindistries with your own domain.
domain: starktechindistries

## EDC image and tag.  Use a stable version.  See https://github.com/eclipse-edc/Connector/releases
image:
  repository: ghcr.io/eclipse-edc/connector
  tag: 0.3.0

## Credentials for the connector (replace with real values in production).
credentials:
  id: my-edc
  secret: changeme

## Exposed service ports (plain HTTP for dev).  TLS should be enabled in production.
service:
  port: 8181

## Additional configuration for compute‑to‑data or federated learning integration.
features:
  computeToData: true
  federatedLearning: true
