apiVersion: v1
kind: Service
metadata:
  name: {{ include "edc.fullname" . }}
  labels:
    app: {{ include "edc.name" . }}
    role: {{ .Values.role | quote }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "edc.name" . }}
    role: {{ .Values.role | quote }}